export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const START_LOGIN = 'START_LOGIN';
export const LOGIN = 'LOGIN';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const REDIRECT = 'REDIRECT';
export const LOGOUT = 'LOGOUT';

export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const START_RETRIEVING_PROFILE_DATA = 'START_RETRIEVING_PROFILE_DATA';
export const PROFILE_INFO_FAILURE = 'PROFILE_INFO_FAILURE';